### PR TITLE
Updated to support swift 2

### PR DESCRIPTION
**Pull request by schickling**

### CODE REVIEW

**Comment by jcavar** [comment]
Hi @schickling,
I am sorry for late response.
Thank you for your efforts. I would like to keep this PR open for two reasons:
1. Swift 2 is still in beta
2. There is 'subviews' branch which is planned to be merged soon

So plan is to merge 'subviews' branch and wait for Swift 2 release and then support it.

**Comment by schickling** [comment]
I guess the best way would be to have a `swift2` branch like other repositories do in order to provide support for early birds. @jcavar what do you think?

**Comment by jcavar** [comment]
Definitely agree with you. I will try to merge 'subviews' branch over the weekend and then if want and have time you can try to create new 'swift2' branch from that. How this sounds?

**Comment by schickling** [comment]
Sounds good.

**Comment by jcavar** [comment]
Hi @schickling,
I've merged 'subviews' branch, published new pod and created 'swift2' branch.
https://github.com/jcavar/refresher/tree/swift2

I'll close this PR for now, but it would be great if you have time to do this in 'swift2' branch.

**Pull request closed without merging**
